name = "zajda-web"
compatibility_date = "2026-06-13"
pages_build_output_dir = "."

[vars]
CDN_BASE_URL = "https://pub-04881c4bbea24b2ab23b9be5a7bd0aa1.r2.dev"

[[kv_namespaces]]
binding = "SESSIONS"
id = "PASTE_SESSIONS_KV_ID_HERE"

[[kv_namespaces]]
binding = "ARTICLES"
id = "56e1ba6fdafc4d46a5de4e4690d01fa3"

[[kv_namespaces]]
binding = "SUBSECTIONS"
id = "dd6ee2a83add46339418a5294c74c7ef"

[[kv_namespaces]]
binding = "PHOTOS"
id = "2d74f6e45eda4cbea51275017ba66c23"

[[r2_buckets]]
binding = "PHOTOS_R2"
bucket_name = "zajda-photos"

[[r2_buckets]]
binding = "QUOTES_R2"
bucket_name = "zajda-quotes"

[[r2_buckets]]
binding = "ARTICLES_R2"
bucket_name = "zajda-articles"

[[r2_buckets]]
binding = "SECTIONS_R2"
bucket_name = "zajda-sections"
